"""empty message

Revision ID: 60243bb7c87c
Revises: 15b78dbec4b1
Create Date: 2025-04-02 19:48:53.746834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60243bb7c87c'
down_revision: Union[str, None] = '15b78dbec4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'type')
    op.add_column('subscribers', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'phone_number')
    op.add_column('orders', sa.Column('type', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
